import type { Metadata } from "next";
import HeadingComponent from "./components/HeadingComponent";
import BottomStickyNavComponent from "./components/BottomStickyNavComponent";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative w-full min-h-full flex flex-col items-center">
          <div className="w-full flex flex-col items-center flex-1">
            <div className="w-full flex justify-center items-center sticky top-0 z-10 bg-white">
              <HeadingComponent title="Ti' Poulet" />
            </div>
            {children}
          </div>

          <BottomStickyNavComponent />
        </div>
      </body>
    </html>
  );
}
